# ANÁLISIS DE DATOS POR FICHERO

In [40]:
import pandas as pd
import numpy as np

In [41]:
pd.options.display.max_columns = None
pd.options.mode.chained_assignment = None

In [42]:
default_path = "../data/"

## ANÁLISIS DE SUSCRIPCIONES

In [43]:
suscriptions_file = '../data/suscripciones.csv'
suscriptions = pd.read_csv(suscriptions_file, parse_dates = ['fecha_creacion', 'fecha_modificacion', 'fecha_inicio', 'fecha_fin'], 
                           dtype = {'id_producto' : 'object', 'id_suscripcion_original' : 'object', 'id_suscripcion' : 'object'})
suscriptions

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,NaN,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,NaN,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,NaN,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,NaN,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,upgrade,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,upgrade,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,NaN,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,NaN,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,NaN,NaN

In [44]:
suscriptions.shape

(10951, 13)

In [45]:
suscriptions.isna().sum().sort_values(ascending = False)

id_suscripcion_original    10101
transicion                 10101
id_producto                   61
referencia_producto           61
fecha_fin                      0
fecha_inicio                   0
fecha_modificacion             0
fecha_creacion                 0
autorenovable                  0
periodicidad                   0
estado_suscripcion             0
id_suscripcion                 0
cod_local                      0
dtype: int64

In [46]:
suscriptions.dtypes

cod_local                          object
id_suscripcion                     object
estado_suscripcion                 object
periodicidad                       object
referencia_producto                object
id_producto                        object
autorenovable                        bool
fecha_creacion             datetime64[ns]
fecha_modificacion         datetime64[ns]
fecha_inicio               datetime64[ns]
fecha_fin                  datetime64[ns]
transicion                         object
id_suscripcion_original            object
dtype: object

In [47]:
suscriptions['referencia_producto'].value_counts()

pack-on-diariomontanes                                             3026
pack-on-diariomontanes-anual                                       1163
suscripcion-on-eldiariomontanes-primermesgratis                     854
pack-on-2-meses-gratis-eldiariomontanes                             720
pack-on-diariomontanes-anual-2020                                   657
pack-on-diariomontanes-primer-mes-1-euro-verano-2020                605
pack-on-diariomontanes-OFERTA VERANO                                590
SUSCRIPCIÓN- EL DIARIO MONTAÑÉS 4º aniversario                      507
pack-on-diariomontanes-dos-meses-tercer-aniversario                 338
3mxe-3moferta-on-3m-cap-30d-201120-EDIA                             334
2m1e-4anivers-on-1m-cap-1d-210202-EDIA                              186
suscripcion-on-diariomontanes-trimestral-noviembre-promoción-20     156
pack-on-anual-tucocinatradicional                                   149
pack-on-anual-tucocinatradicional-diciembre                         121
suscripcion-on-diariomontanes-blackfriday-20                        120
pack-on-diariomontanes-primermesgratis                              109
pack-on-anual-octubre19                                             103
pack-navega-diariomontanes                                           98
suscripcion-anual-on-cartera-balenciaga                              94
suscripcion-anual-on-productoslupa                                   90
pack-on-diariomontanes-dos meses 1 €                                 87
on-plus-diciembre-2017                                               86
nop--on-1m-noa-170123-EDIA                                           84
reg-cocinatrad-on-12m-cap-30d-201204-EDIA                            70
pack-on-blackfriday-2019                                             61
on-plus-febrero-2018                                                 54
suscripcion-on-diariomontanes-trimestral-20                          51
pack-on-diariomontanes-primer mes 1 euro-verano 2020                 50
nop--on-3m-noa-a-200416-EDIA                                         49
nop--on-12m-noa-a-181219-EDIA                                        30
nop--on-12m-noa-200921-EDIA                                          30
pack-on-diariomontanes-septiembre                                    28
on-plus-mayo-2018                                                    24
pack-on-diariomontanes-promo-abril                                   19
on-plus-abril-2018                                                   19
on-plus-semana-santa-2018                                            16
on-plus-noviembre-2017                                               13
pack-total-7-diariomontanes                                          12
pack-on-diariomontanes-anual-2020 2.0                                10
pack-ondiariomontanes-promo-junio-2                                   9
SUSCRIPCIÓN  EL Diario Montañés on+                                   9
on-plus-junio-2018                                                    8
pack-on-1mesgratis-captacion-rtim-diariomontañes                      8
nop-trimestral-on-3m-noa--201203-EDIA                                 6
nop--nav-1m-noa-170123-EDIA                                           6
pack-on-eldiariomontanes-3meses                                       6
pack-on-diariomontanes-anual-SCIF                                     5
pack-on-eldiariomontanes-anual-promo                                  4
nop--tot-1m-noa-170131-EDIA                                           4
pack-on-eldiariomontanes-anual 29,95€                                 3
nop-retencion-on-12m-rec-a-200219-EDIA                                3
3mxe-3moferta-on-3m-cap-30d-080121-ECOM                               2
pack-on-anual-retencion                                               2
reg-tjtaeci15-on-12m-cap--210226-EDIA                                 1
pack-ondiariomontanes-promo-junio                                     1
Name: referencia_producto, dtype: int64

In [48]:
suscriptions['cod_local'].value_counts()

d22a5f549dbb4738bb243a1031c381be                      13
b78d22bcb585412da99467f1410e8be0                      12
_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0Bzy4=     8
934909fdf0f64e92b8f2d5f19d43bccf                       8
806730                                                 8
                                                      ..
a1af9ace31aa4852bb96f82bbe31b6e0                       1
c16dbfa900204769aeea4c0bfc292b5d                       1
39a939a270a44aaaab1e957e936b95d9                       1
18cc6ddac3a34edd98b11878540db90e                       1
11fb62332c934054b8d80da4a3bdacfe                       1
Name: cod_local, Length: 8326, dtype: int64

In [49]:
suscriptions[suscriptions['cod_local'] == '950e805fb31d4633b84c1001ed7a018d'].sort_values('fecha_fin')

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
7599,950e805fb31d4633b84c1001ed7a018d,10538,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 15:56:44,2019-12-26 15:05:47,2017-03-08,2019-12-26,NaN,NaN
6941,950e805fb31d4633b84c1001ed7a018d,46900,canceled,Anual,pack-on-diariomontanes,90721,True,2019-12-26 14:04:17,2020-12-30 07:00:13,2019-12-26,2020-12-30,upgrade,10538
10384,950e805fb31d4633b84c1001ed7a018d,36007932,canceled,Trimestral,nop--on-3m-noa-a-200416-EDIA,98924,True,2021-01-06 22:46:28,2021-01-07 15:19:56,2021-01-06,2021-01-07,NaN,NaN
6658,950e805fb31d4633b84c1001ed7a018d,36008029,active,Anual,nop--on-12m-noa-200921-EDIA,100426,True,2021-01-07 15:20:00,2021-01-07 15:20:00,2021-01-07,2022-01-06,upgrade,36007932

In [50]:
suscriptions[suscriptions['estado_suscripcion'] == 'canceled']['periodicidad'].value_counts()

Mensual       4645
Anual          430
Trimestral      71
Name: periodicidad, dtype: int64

In [51]:
suscriptions.groupby('periodicidad')['referencia_producto'].count()

periodicidad
Anual         2735
Mensual       7557
Trimestral     598
Name: referencia_producto, dtype: int64

In [52]:
suscriptions['fecha_fin'] - suscriptions['fecha_inicio']

0       1488 days
1        531 days
2       1460 days
3       1406 days
4        623 days
           ...
10946    364 days
10947    364 days
10948     96 days
10949    180 days
10950    178 days
Length: 10951, dtype: timedelta64[ns]

In [53]:
suscriptions =  suscriptions[(suscriptions['fecha_fin'] >= suscriptions['fecha_inicio'])]

In [54]:
suscriptions

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,NaN,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,NaN,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,NaN,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,NaN,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,upgrade,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,upgrade,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,NaN,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,NaN,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,NaN,NaN

## SUSCRIPCIONES

In [55]:
from subscriptions import Subscriptions

In [56]:
sus = Subscriptions(data_root=default_path)
sus.set_data()

In [57]:
sus.get_data()

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,NaN,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,NaN,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,NaN,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,NaN,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,upgrade,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,upgrade,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,NaN,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,NaN,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,NaN,NaN

In [58]:
sus.clean_data()

In [59]:
sus.get_data()

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,False,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,False,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,False,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10938,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,False,NaN
10939,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,False,NaN
10940,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,False,NaN
10941,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,False,NaN
10942,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,False,NaN

In [60]:
for c in sus.subscriptions.columns:
    if (len(sus.subscriptions[c].isna().value_counts()) > 1):
        print (c)
        print (sus.subscriptions[c].isna().value_counts())

referencia_producto
False    10882
True        61
Name: referencia_producto, dtype: int64
id_producto
False    10882
True        61
Name: id_producto, dtype: int64
id_suscripcion_final
True     10093
False      850
Name: id_suscripcion_final, dtype: int64

In [61]:
sus.subscriptions[sus.subscriptions['referencia_producto'].isna()]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
23,f3756dfa44b34c21895c5915e933e7f1,21935,canceled,Mensual,NaN,NaN,True,2018-12-12 11:03:58,2018-12-12 11:03:58,2018-12-12,2019-01-11,False,NaN
209,_guid_W6mm5UqUkI9e-Zp2lgtbFbXyEjTFTB7ojAWRyaob...,10566,active,Mensual,NaN,NaN,True,2017-03-09 10:39:42,2017-03-09 10:39:42,2017-03-09,2017-04-08,False,NaN
366,_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0B...,10438,active,Mensual,NaN,NaN,True,2017-03-05 14:19:09,2017-03-05 14:19:09,2017-03-05,2017-04-04,False,NaN
570,d22a5f549dbb4738bb243a1031c381be,27139,active,Mensual,NaN,NaN,True,2019-02-24 19:31:48,2019-02-24 19:31:48,2019-02-24,2019-03-23,False,NaN
885,0bf1ec92ceec4019be58bf069633f5f8,10252,active,Mensual,NaN,NaN,True,2017-02-28 09:02:19,2017-02-28 09:02:19,2017-02-28,2017-03-27,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9332,7135774db94941ee8c7500bd6872b7e0,12192,active,Mensual,NaN,NaN,True,2017-07-01 20:00:21,2017-07-01 20:00:21,2017-07-01,2017-07-31,False,NaN
9447,_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0B...,10335,canceled,Mensual,NaN,NaN,True,2017-03-02 10:52:18,2017-03-02 10:52:18,2017-03-02,2017-04-01,False,NaN
10303,c976509f263641a197f1942fa5f9e790,11353,active,Mensual,NaN,NaN,True,2017-04-17 15:20:58,2017-04-17 15:20:58,2017-04-17,2017-05-16,False,NaN
10306,7135774db94941ee8c7500bd6872b7e0,12196,active,Mensual,NaN,NaN,True,2017-07-01 20:14:37,2017-07-01 20:14:37,2017-07-01,2017-07-31,False,NaN
10531,d22a5f549dbb4738bb243a1031c381be,27135,active,Anual,NaN,NaN,True,2019-02-24 19:26:42,2019-02-24 19:26:42,2019-02-24,2020-02-23,False,NaN

In [62]:
sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual']['referencia_producto'].value_counts()

pack-on-diariomontanes                                  2823
suscripcion-on-eldiariomontanes-primermesgratis          854
pack-on-2-meses-gratis-eldiariomontanes                  720
pack-on-diariomontanes-primer-mes-1-euro-verano-2020     605
pack-on-diariomontanes-OFERTA VERANO                     590
SUSCRIPCIÓN- EL DIARIO MONTAÑÉS 4º aniversario           507
pack-on-diariomontanes-dos-meses-tercer-aniversario      338
2m1e-4anivers-on-1m-cap-1d-210202-EDIA                   186
suscripcion-on-diariomontanes-blackfriday-20             120
pack-on-diariomontanes-primermesgratis                   109
pack-navega-diariomontanes                                98
pack-on-diariomontanes-dos meses 1 €                      87
on-plus-diciembre-2017                                    86
nop--on-1m-noa-170123-EDIA                                84
pack-on-blackfriday-2019                                  61
on-plus-febrero-2018                                      54
pack-on-diariomontanes-primer mes 1 euro-verano 2020      50
pack-on-diariomontanes-septiembre                         28
on-plus-mayo-2018                                         23
pack-on-diariomontanes-promo-abril                        19
on-plus-abril-2018                                        17
on-plus-semana-santa-2018                                 16
on-plus-noviembre-2017                                    13
pack-ondiariomontanes-promo-junio-2                        9
pack-on-1mesgratis-captacion-rtim-diariomontañes           8
on-plus-junio-2018                                         8
SUSCRIPCIÓN  EL Diario Montañés on+                        8
nop--nav-1m-noa-170123-EDIA                                6
pack-on-eldiariomontanes-3meses                            6
pack-total-7-diariomontanes                                4
pack-on-eldiariomontanes-anual-promo                       4
nop--tot-1m-noa-170131-EDIA                                4
pack-on-eldiariomontanes-anual 29,95€                      3
pack-ondiariomontanes-promo-junio                          1
Name: referencia_producto, dtype: int64

In [63]:
sus.subscriptions[(sus.subscriptions['fecha_modificacion'] < sus.subscriptions['fecha_creacion'])]

Empty DataFrame
Columns: [cod_local, id_suscripcion, estado_suscripcion, periodicidad, referencia_producto, id_producto, autorenovable, fecha_creacion, fecha_modificacion, fecha_inicio, fecha_fin, transicion, id_suscripcion_final]
Index: []

In [64]:
sus.subscriptions[sus.subscriptions['transicion'] == True].groupby('periodicidad').count()

,cod_local,id_suscripcion,estado_suscripcion,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
periodicidad,,,,,,,,,,,,
Anual,17,17,17,17,17,17,17,17,17,17,17,17
Mensual,831,831,831,831,831,831,831,831,831,831,831,831
Trimestral,2,2,2,2,2,2,2,2,2,2,2,2

In [65]:
sus.subscriptions[(sus.subscriptions['periodicidad'] == 'Trimestral') & (sus.subscriptions['transicion'] == True)]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
1649,_guid_jeMYYUxd7QZmr6Y_IJsHzWu_7zQruabGV5SgLXY7...,87245,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-11-06 01:02:56,2021-01-24 13:13:47,2020-11-06,2021-01-24,True,36012160
10377,950e805fb31d4633b84c1001ed7a018d,36007932,canceled,Trimestral,nop--on-3m-noa-a-200416-EDIA,98924,True,2021-01-06 22:46:28,2021-01-07 15:19:56,2021-01-06,2021-01-07,True,36008029

In [66]:
#36007932 Trimestral > Anual 36008029
sus.subscriptions[sus.subscriptions['id_suscripcion'] == '36008029']

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
6655,950e805fb31d4633b84c1001ed7a018d,36008029,active,Anual,nop--on-12m-noa-200921-EDIA,100426,True,2021-01-07 15:20:00,2021-01-07 15:20:00,2021-01-07,2022-01-06,False,NaN

In [67]:
sus.subscriptions[(sus.subscriptions['periodicidad'] == 'Anual') & (sus.subscriptions['transicion'] == True)]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
224,8d46c66a683b4457adf360246ddec545,24864,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-23 13:00:36,2021-01-23 17:23:56,2019-01-23,2021-01-23,True,36011879
619,d58f2a6078b64f9d805409b7bec50db1,23235,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-02 11:49:39,2019-12-31 12:47:19,2019-01-02,2019-12-31,True,47206
3177,22ac6346cb2540d1b134254335e9678e,43114,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-08 11:40:05,2020-10-21 11:03:43,2019-11-08,2020-10-21,True,85366
3295,ae0868be502f482689679633ff725069,42990,canceled,Anual,pack-on-anual-octubre19,94652,False,2019-11-05 12:42:49,2020-11-01 10:06:12,2019-11-05,2020-11-01,True,86731
4149,57128,22824,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2018-12-26 09:50:00,2020-12-23 15:40:28,2018-12-26,2020-12-23,True,36005826
5112,c8cc576e827a473fbe37103213b5a9b3,42909,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-04 13:51:51,2020-10-26 11:14:23,2019-11-04,2020-10-26,True,85976
5282,aa0a4d74d53141bd9e9dca12f9548280,50658,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2020-02-24 12:48:33,2021-02-22 15:40:34,2020-02-24,2021-02-22,True,36019242
5653,75d6665a5b8c4e5eb5ae584bb6ab2af9,27579,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-03-02 06:38:00,2021-02-28 18:30:01,2019-03-02,2021-02-28,True,36020399
5830,3a9f25eddcf6459aa162b15121229b2a,43037,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-06 13:08:27,2020-11-04 15:59:07,2019-11-06,2020-11-04,True,87013
6766,120175,43898,canceled,Anual,pack-on-anual-octubre19,94652,False,2019-11-21 11:10:12,2020-11-18 12:19:44,2019-11-21,2020-11-18,True,88454
7252,75c6024ffdb04df9ae63f2529d15ccd6,44084,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-22 18:27:12,2020-11-04 18:46:24,2019-11-22,2020-11-04,True,87022
8404,087dd0151ea446fc90f85046f796c0ea,23551,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-07 09:19:52,2020-01-01 18:28:49,2019-01-07,2020-01-01,True,47279
9029,4c0601916fd241daabae48d9534161c1,43476,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-18 11:02:52,2020-11-11 08:59:31,2019-11-18,2020-11-11,True,87824
9082,29468fd5dd194faab23a1318b196c4ea,42928,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-04 17:53:19,2020-11-02 11:28:20,2019-11-04,2020-11-02,True,86823
9422,33f17937c3b549ff8f7788442579a5d9,43471,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-18 09:51:52,2020-11-12 09:30:32,2019-11-18,2020-11-12,True,87907
9779,3f7ec2ee6ec64621bc01f6bc87b1ed8f,50937,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2020-02-26 10:23:10,2021-02-09 16:23:09,2020-02-26,2021-02-09,True,36016701
10748,1ab9f37e6c4e4f6085c306d94409f005,44551,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-26 12:43:05,2020-11-23 08:03:11,2019-11-26,2020-11-23,True,88812

In [68]:
# Anual > Anual
sus.subscriptions[sus.subscriptions['id_suscripcion'] == '87824']

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
2196,4c0601916fd241daabae48d9534161c1,87824,active,Anual,pack-on-diariomontanes-anual-2020 2.0,100491,True,2020-11-11 07:54:16,2020-12-23 14:00:00,2020-11-11,2021-11-10,False,NaN

In [69]:
# Solo mensuales 
mensuales = sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual'].groupby('transicion').count()
mensuales

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,id_suscripcion_final
transicion,,,,,,,,,,,,
False,6766,6766,6766,6766,6718,6718,6766,6766,6766,6766,6766,0
True,831,831,831,831,831,831,831,831,831,831,831,831

In [70]:
# Porcentaje de upgrades desde todos los productos mensuales
mensuales['cod_local'][True] * 100/(mensuales['cod_local'][True] + mensuales['cod_local'][False])

10.938528366460446

In [71]:
mensuals = sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual'][['cod_local', 'fecha_inicio', 'fecha_fin']]

In [72]:
mensuals

                              cod_local fecha_inicio  fecha_fin
0      bb399b9372784e5189cf551b5029ce4f   2017-02-19 2021-03-18
1      bad5a9ea94cd4da0befc92e5d1b8a749   2017-03-08 2018-08-21
2      b6d8b038649b4158a4150ea6953b15ab   2017-03-09 2021-03-08
3      2665f56bbe5842ca8bcaba17d0abd77f   2017-03-14 2021-01-18
4      af02dac14a454e85a0f857781cb9d7a4   2017-03-17 2018-11-30
...                                 ...          ...        ...
10929  ac09c4007be046fb81cf828361a2b16b   2020-02-28 2021-03-27
10931  8a802f603bf24515972b042d5902f724   2020-03-18 2021-03-17
10932  748d27048ab946c4a32e5d96f557dbaf   2020-03-23 2020-05-22
10933  dd4d13dd95ff490bb9b60158c6a41b9c   2020-03-23 2020-05-22
10934                            188074   2020-03-29 2020-04-28

[7597 rows x 3 columns]

## ANÁLISIS DE INDICADORES DE USUARIO

In [73]:
users_file = '../data/dm_indicadores_usuario.csv'
users = pd.read_csv(users_file, sep=';')
users

/Users/raulgomez/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
0,10541116208122761551136290964798460775,81071784393406839193479723535297547386,9f4f3c63575f4c119dd3197f7cbc2001,39609,NaN,NaN,suscriptor,web,pc,1,1,1,0,0,0,0,1.000000,0,0,NaN,0.0,0.0,1.000000,NaN,0,0.0,2021-02-10
1,10034692791710549347086110688257695691,65303573732917209391352108028058193537,670a42d953b64b6e85af13a97031634d,39120,NaN,NaN,suscriptor,web,mobile,3,2,1,1,1,1,1,3.000000,0,0,1.550000,0.0,0.0,0.333333,1.550000,0,0.0,2021-02-10
2,105156470833335705641056728939452708,21891238253361882510436743594338179740,4ba048e82344496bb42210c94ebc9fde,39478,38,m,suscriptor,web,mobile,7,3,4,2,2,1,1,1.750000,0,3,0.991667,0.0,0.0,0.250000,3.966667,0,0.0,2021-02-10
3,1113408175264640272121744148860842417,17993675919976676643859821549267456565,757916,39350,30,m,suscriptor,web,pc,13,7,1,7,4,3,1,13.000000,0,0,24.000000,0.0,0.0,0.076923,24.000000,0,0.0,2021-02-10
4,11491832465312911972456445035439126966,47739097890560374790721807134254945858,85beb7e84e634ea3b9134e809c53aaf6,39618,56,m,suscriptor,web,pc,115,7,3,90,6,0,0,38.333333,0,0,443.283333,0.0,0.0,0.026087,443.283333,0,0.0,2021-02-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377787,88288967104494902742111918289236999296,83753579094052022152624489282841099126,c72121c614754f9ba420a651ebae45ef,39006,58,m,suscriptor,web,mobile,1,1,1,1,1,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-26
377788,8868782250010377285297258055399160791,24981678156166565972633526055722058040,031cf4a3aa3641e38efa70f655a0ee25,39003,55,m,suscriptor,web,pc,11,4,2,3,3,1,1,5.500000,1,0,32.691667,0.0,0.0,0.181818,32.133333,0,0.0,2021-01-26
377789,89323367507485641956159919969039566844,16258713090209869802510480446419055254,874a187a51ae48079758a88182e22ce1,39300,42,m,suscriptor,web,mobile,2,1,2,0,0,0,0,1.000000,0,2,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-26
377790,90907249974058520511157279522773794754,84533209576538945830378135572048597377,db3b4f858e2c408aa06b967ec01d8eb6,39002,58,NaN,suscriptor,web,mobile,21,9,2,9,6,1,1,10.500000,0,0,26.008333,0.0,0.0,0.095238,26.008333,1,0.0,2021-01-26
377791,91151341325409844673095026538556196453,27164521406744024661826444262595766073,641748,39008,36,f,suscriptor,web,pc,11,6,3,3,2,0,0,3.666667,0,1,8.300000,0.0,0.0,0.200000,12.450000,1,0.0,2021-01-26

In [74]:
users['id_gigya'].value_counts()

cca996af5fe64870af5cce9e83ac6cd3    566
57dcdd9c0c054aecaf17e1ac864da6f4    522
b06cb63603ba4f21a7793c601d910292    500
6c98f1df02844acc86d544f5c641dcbe    405
7322b1723e5440998d1bb72b2ab79ceb    396
                                   ...
d3f22bf5e75541e3917557ff997c236c      1
7308089e14ad47009553cde49ba00c62      1
0540f51ccb324e74a51f4ac04c82cd33      1
a5da550adf6047cf944a71c1d559574b      1
9154574be3ed41fa932e291e36c681ff      1
Name: id_gigya, Length: 6459, dtype: int64

In [36]:
users[users['id_gigya'] == '590691']

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
30532,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,9,5,5,4,4,3,3,1.800000,0,0,0.330000,NaN,NaN,NaN,0.330000,0,NaN,2021-02-08
32838,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,13,8,3,7,8,2,2,4.333333,0,0,2.294444,NaN,NaN,NaN,2.138889,0,NaN,2021-02-12
35148,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,9,6,4,5,6,3,3,2.250000,0,0,0.800000,NaN,NaN,NaN,0.754167,0,NaN,2021-02-22
39776,32541854591385089274611687303696681246,NaN,590691,39012,45,masculino,suscriptor,app,mobile,8,2,1,0,0,0,0,8.000000,0,0,2.683333,NaN,NaN,NaN,2.683333,0,NaN,2021-02-03
39899,33007534831315936186917530153997192362,NaN,590691,39012,45,masculino,suscriptor,app,mobile,3,3,1,2,2,1,1,3.000000,0,0,2.150000,NaN,NaN,NaN,2.150000,0,NaN,2021-02-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362499,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,6,3,4,2,3,0,0,1.500000,0,0,0.608333,NaN,NaN,NaN,0.525000,0,NaN,2021-02-04
364637,32541854591385089274611687303696681246,NaN,590691,39012,45,masculino,suscriptor,app,mobile,3,2,1,1,1,1,1,3.000000,0,0,0.233333,NaN,NaN,NaN,0.233333,0,NaN,2021-02-05
365169,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,9,6,4,5,5,4,4,2.250000,0,0,0.579167,NaN,NaN,NaN,0.579167,0,NaN,2021-02-05
367558,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,14,9,6,8,10,1,1,2.333333,0,0,0.797222,NaN,NaN,NaN,0.741667,0,NaN,2021-01-25
369991,33589375103171956896917530303246482058,NaN,590691,39012,45,masculino,suscriptor,app,mobile,16,11,4,10,14,4,4,4.000000,0,0,2.408333,NaN,NaN,NaN,2.395833,0,NaN,2021-02-17

In [37]:
suscriptions[suscriptions['cod_local'] == '590691']

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
7056,590691,37680,active,Anual,pack-on-diariomontanes-anual,90721,True,2019-07-26 09:30:57,2020-07-24 08:45:21,2019-07-26,2021-07-25,NaN,NaN

In [38]:
users.columns

Index(['usuario', 'cookie', 'id_gigya', 'cod_postal', 'edad', 'genero',
       'tipo_login', 'tipo_navega', 'tipo_dispositivo', 'paginas_vistas',
       'contenidos', 'visitas', 'pv_muro', 'contenidos_muro', 'pv_premium',
       'contenidos_premium', 'engagement', 'videos', 'rebotes', 'tm_visita',
       'paginas_vistas_amp', 'visitas_amp', 'engagement_sin_rebote',
       'tm_visita_sin_rebote', 'n_salta_metered', 'n_comentarios_enviados',
       'fecha_navegacion'],
      dtype='object')

In [39]:
cols_agruped_by = users.columns[2:7] 
cols_agruped_by

Index(['id_gigya', 'cod_postal', 'edad', 'genero', 'tipo_login'], dtype='object')

In [40]:
cols_agruped_by = cols_agruped_by.insert(0,'fecha_navegacion')
cols_agruped_by

Index(['fecha_navegacion', 'id_gigya', 'cod_postal', 'edad', 'genero',
       'tipo_login'],
      dtype='object')

In [41]:
data_cols_agruped = users.columns[9:-1]
data_cols_agruped

Index(['paginas_vistas', 'contenidos', 'visitas', 'pv_muro', 'contenidos_muro',
       'pv_premium', 'contenidos_premium', 'engagement', 'videos', 'rebotes',
       'tm_visita', 'paginas_vistas_amp', 'visitas_amp',
       'engagement_sin_rebote', 'tm_visita_sin_rebote', 'n_salta_metered',
       'n_comentarios_enviados'],
      dtype='object')

In [42]:
users['tipo_login'].value_counts()

suscriptor    377792
Name: tipo_login, dtype: int64

In [43]:
users['genero'].value_counts()

m            131180
masculino     78791
f             48372
femenino      28533
u               750
undefined         1
Name: genero, dtype: int64

In [44]:
users.loc[users['genero'] == 'masculino', ['genero']] = 'm'

In [45]:
#users['genero'] = users['genero'].replace(['masculino'],'m').replace('femenino','f').fillna('u')
#users.loc[users['genero'] == 'masculino', 'genero'] = 'm'
#users.loc[users['genero'] == 'femenino', 'genero'] = 'f'
#users['genero'].fillna('u', inplace=True)
#users['genero'] = np.where(users['genero'] == 'masculino','m',users['genero'])
users.loc[users['genero'] == 'masculino', ['genero']] = 'm'
#users[users['genero'] == 'femenino' ].loc[:, ['genero']] = 'f'

In [46]:
users['genero']

0         NaN
1         NaN
2           m
3           m
4           m
         ...
377787      m
377788      m
377789      m
377790    NaN
377791      f
Name: genero, Length: 377792, dtype: object

In [75]:
from users import Users

In [76]:
users = Users(data_root = default_path)
users.set_data(separator_fields=';')

/Users/raulgomez/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3347: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [77]:
users.users.sort_values(by='id_gigya')

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
182898,79383777768499153347424230246845664567,71173365718986246641317266020938487519,-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw,39012,NaN,NaN,suscriptor,web,mobile,1,1,1,0,0,0,0,1.00,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-18
195862,34528486130674501094611698403073343061,NaN,00216a84e17c4773be309083c7488425,39009,54,masculino,suscriptor,app,mobile,15,7,5,6,5,0,0,3.00,0,0,0.946667,NaN,NaN,NaN,0.946667,0,NaN,2021-01-06
342650,33139324442504818196917530765492232415,NaN,00216a84e17c4773be309083c7488425,39009,54,masculino,suscriptor,app,mobile,9,8,1,7,7,7,7,9.00,0,0,19.250000,NaN,NaN,NaN,19.250000,0,NaN,2021-01-15
197962,34528486130674501094611698403073343061,NaN,00216a84e17c4773be309083c7488425,39009,54,masculino,suscriptor,app,mobile,11,6,4,5,4,4,3,2.75,0,0,6.379167,NaN,NaN,NaN,6.379167,0,NaN,2021-02-28
190939,34528486130674501094611698403073343061,NaN,00216a84e17c4773be309083c7488425,39009,54,masculino,suscriptor,app,mobile,20,11,4,10,9,2,2,5.00,0,0,7.416667,NaN,NaN,NaN,7.416667,0,NaN,2021-01-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374915,39832728454123303865538453348734024149,89614404063494133362076578257040385596,NaN,NaN,NaN,NaN,suscriptor,web,mobile,2,2,1,1,1,0,0,2.00,0,0,5.283333,0.0,0.0,0.500000,5.283333,0,0.0,2021-02-03
375856,192813402151427310919912155463592798,39783334192237076992062507189494078231,NaN,NaN,NaN,NaN,suscriptor,web,mobile,3,1,1,0,0,0,0,3.00,0,0,8.850000,0.0,0.0,0.333333,8.850000,0,0.0,2021-02-05
376520,66437707671667288109005471124480549020,06672775139826069742132219860560328649,NaN,NaN,NaN,NaN,suscriptor,web,mobile,1,1,1,0,0,0,0,1.00,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-26
377453,192813402151427310919912155463592798,39783334192237076992062507189494078231,NaN,NaN,NaN,NaN,suscriptor,web,mobile,12,6,2,4,2,2,1,6.00,0,0,7.600000,0.0,0.0,0.166667,7.600000,0,0.0,2021-01-07
377546,64681261176176929308990804995896681324,67788124280432880023200233904968527153,NaN,NaN,NaN,NaN,suscriptor,web,pc,5,2,1,0,0,0,0,5.00,0,0,1.700000,0.0,0.0,0.200000,1.700000,0,0.0,2021-01-07

In [27]:
users.users['tipo_dispositivo'].value_counts()

mobile    248499
pc        129293
Name: tipo_dispositivo, dtype: int64

In [28]:
users.users['id_gigya'].isna().value_counts()

False    377639
True        153
Name: id_gigya, dtype: int64

In [30]:
users.users['id_gigya'].isna().value_counts()

False    377639
Name: id_gigya, dtype: int64

In [78]:
users.clean_data()

In [79]:
users.users[users.users['id_gigya'].notna()].sort_values('id_gigya')

,id_gigya,cod_postal,edad,genero,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
182819,-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw,39012,NaN,u,web,mobile,1,1,1,0,0,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-18
195780,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,15,7,5,6,5,0,0,3.000000,0,0,0.946667,NaN,NaN,NaN,0.946667,0,NaN,2021-01-06
342506,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,9,8,1,7,7,7,7,9.000000,0,0,19.250000,NaN,NaN,NaN,19.250000,0,NaN,2021-01-15
197880,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,11,6,4,5,4,4,3,2.750000,0,0,6.379167,NaN,NaN,NaN,6.379167,0,NaN,2021-02-28
190858,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,20,11,4,10,9,2,2,5.000000,0,0,7.416667,NaN,NaN,NaN,7.416667,0,NaN,2021-01-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177318,prospect-4e182b5b9f7e42c8b95756e1559e8610,39012,71,m,web,mobile,2,1,1,0,0,0,0,2.000000,0,0,0.666667,0.0,0.0,0.500000,0.666667,0,0.0,2021-02-01
258995,prospect-554153,39840,55,m,web,pc,14,6,3,3,2,0,0,4.666667,2,1,9.077778,0.0,0.0,0.153846,13.266667,0,0.0,2021-02-06
151067,prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968,39009,57,u,web,mobile,9,3,2,1,1,0,0,4.500000,0,0,1.016667,0.0,0.0,0.222222,1.016667,0,0.0,2021-02-04
193545,prospect-cf3e57f2558f476481c85e389010988f,39008,45,m,web,mobile,16,7,7,5,5,4,4,2.285714,0,3,3.804762,0.0,0.0,0.307692,6.658333,0,0.0,2021-02-17
307348,prospect-e608e6dd66804947834d487671d64082,39479,43,u,web,mobile,20,9,4,5,4,2,2,5.000000,0,1,1.587500,0.0,0.0,0.157895,1.988889,1,0.0,2021-01-22

In [80]:
users.users['edad'].isna().value_counts()

False    347034
True      30605
Name: edad, dtype: int64

In [89]:
users.users['id_gigya'].isna().value_counts()

False    377639
Name: id_gigya, dtype: int64

In [82]:
users.users['cod_postal'].isna().value_counts()

False    374973
True       2666
Name: cod_postal, dtype: int64

In [83]:
users.users['engagement'].isna().value_counts()

False    377639
Name: engagement, dtype: int64

In [84]:
users.users['rebotes'].isna().value_counts()

False    377639
Name: rebotes, dtype: int64

In [85]:
users.users['cod_postal'].isna().value_counts()

False    374973
True       2666
Name: cod_postal, dtype: int64

In [86]:
for c in users.users.columns:
    if (len(users.users[c].isna().value_counts()) > 1):
        print (c)
        print (users.users[c].isna().value_counts())

cod_postal
False    374973
True       2666
Name: cod_postal, dtype: int64
edad
False    347034
True      30605
Name: edad, dtype: int64
tm_visita
False    342414
True      35225
Name: tm_visita, dtype: int64
paginas_vistas_amp
False    238014
True     139625
Name: paginas_vistas_amp, dtype: int64
visitas_amp
False    238014
True     139625
Name: visitas_amp, dtype: int64
engagement_sin_rebote
False    205313
True     172326
Name: engagement_sin_rebote, dtype: int64
tm_visita_sin_rebote
False    339370
True      38269
Name: tm_visita_sin_rebote, dtype: int64
n_comentarios_enviados
False    238014
True     139625
Name: n_comentarios_enviados, dtype: int64

In [63]:
users.users['cod_postal'].value_counts()

39012    30126
39011    29086
39300    25674
39005    22222
39600    15465
         ...
20570        1
12005        1
48910        1
39575        1
15008        1
Name: cod_postal, Length: 605, dtype: int64

In [87]:
sus.extract_mensual_suscriptions()

                              cod_local
0      bb399b9372784e5189cf551b5029ce4f
1      bad5a9ea94cd4da0befc92e5d1b8a749
2      b6d8b038649b4158a4150ea6953b15ab
3      2665f56bbe5842ca8bcaba17d0abd77f
4      af02dac14a454e85a0f857781cb9d7a4
...                                 ...
10929  ac09c4007be046fb81cf828361a2b16b
10931  8a802f603bf24515972b042d5902f724
10932  748d27048ab946c4a32e5d96f557dbaf
10933  dd4d13dd95ff490bb9b60158c6a41b9c
10934                            188074

[7597 rows x 1 columns]

In [65]:
sus_nav = sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual'].merge(users.users, how='left', left_on='cod_local', right_on='id_gigya')
sus_nav

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final,id_gigya,cod_postal,edad,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion,f,m,u,app,web,mobile,pc
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN,bb399b9372784e5189cf551b5029ce4f,39011,52,27.0,12.0,1.0,13.0,11.0,5.0,4.0,27.000000,0.0,0.0,37.516667,0.0,0.0,0.037037,37.516667,0.0,0.0,2021-02-10,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN,bb399b9372784e5189cf551b5029ce4f,39011,52,28.0,13.0,2.0,7.0,7.0,3.0,3.0,14.000000,0.0,0.0,8.858333,0.0,0.0,0.071429,8.858333,0.0,0.0,2021-02-08,1.0,0.0,0.0,0.0,1.0,0.0,1.0
2,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN,bb399b9372784e5189cf551b5029ce4f,39011,52,13.0,7.0,1.0,8.0,6.0,6.0,4.0,13.000000,0.0,0.0,18.966667,0.0,0.0,0.076923,18.966667,0.0,0.0,2021-02-06,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN,bb399b9372784e5189cf551b5029ce4f,39011,52,32.0,17.0,1.0,17.0,16.0,8.0,7.0,32.000000,0.0,0.0,45.366667,0.0,0.0,0.031250,45.366667,0.0,0.0,2021-01-24,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN,bb399b9372784e5189cf551b5029ce4f,39011,52,13.0,7.0,1.0,6.0,5.0,5.0,4.0,13.000000,0.0,0.0,21.483333,0.0,0.0,0.076923,21.483333,0.0,0.0,2021-01-14,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293032,8a802f603bf24515972b042d5902f724,53928,active,Mensual,suscripcion-on-eldiariomontanes-primermesgratis,97306,True,2020-03-18 11:03:58,2021-02-15 05:12:19,2020-03-18,2021-03-17,False,NaN,8a802f603bf24515972b042d5902f724,39012,55,16.0,11.0,2.0,8.0,7.0,4.0,4.0,8.000000,0.0,0.0,13.316667,NaN,NaN,NaN,13.316667,0.0,NaN,2021-02-17,0.0,0.0,1.0,1.0,0.0,1.0,0.0
293033,8a802f603bf24515972b042d5902f724,53928,active,Mensual,suscripcion-on-eldiariomontanes-primermesgratis,97306,True,2020-03-18 11:03:58,2021-02-15 05:12:19,2020-03-18,2021-03-17,False,NaN,8a802f603bf24515972b042d5902f724,39012,55,8.0,5.0,3.0,5.0,4.0,3.0,3.0,2.666667,0.0,0.0,0.966667,NaN,NaN,NaN,0.966667,0.0,NaN,2021-02-17,0.0,0.0,1.0,1.0,0.0,1.0,0.0
293034,748d27048ab946c4a32e5d96f557dbaf,57932,canceled,Mensual,suscripcion-on-eldiariomontanes-primermesgratis,97306,False,2020-03-23 11:12:05,2020-05-23 08:59:26,2020-03-23,2020-05-22,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293035,dd4d13dd95ff490bb9b60158c6a41b9c,58005,canceled,Mensual,suscripcion-on-eldiariomontanes-primermesgratis,97306,False,2020-03-23 12:24:28,2020-05-23 08:59:45,2020-03-23,2020-05-22,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293036,188074,61109,canceled,Mensual,suscripcion-on-eldiariomontanes-primermesgratis,97306,False,2020-03-29 18:18:50,2020-04-29 09:00:47,2020-03-29,2020-04-28,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
men_sus_nav = sus.mensual_subscriptions.merge(users.users, how='left', left_on='cod_local', right_on='id_gigya')
men_sus_nav

,cod_local,id_gigya,cod_postal,edad,genero,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
0,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,27.0,12.0,1.0,13.0,11.0,5.0,4.0,27.000000,0.0,0.0,37.516667,0.0,0.0,0.037037,37.516667,0.0,0.0,2021-02-10
1,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,pc,28.0,13.0,2.0,7.0,7.0,3.0,3.0,14.000000,0.0,0.0,8.858333,0.0,0.0,0.071429,8.858333,0.0,0.0,2021-02-08
2,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,13.0,7.0,1.0,8.0,6.0,6.0,4.0,13.000000,0.0,0.0,18.966667,0.0,0.0,0.076923,18.966667,0.0,0.0,2021-02-06
3,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,32.0,17.0,1.0,17.0,16.0,8.0,7.0,32.000000,0.0,0.0,45.366667,0.0,0.0,0.031250,45.366667,0.0,0.0,2021-01-24
4,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,13.0,7.0,1.0,6.0,5.0,5.0,4.0,13.000000,0.0,0.0,21.483333,0.0,0.0,0.076923,21.483333,0.0,0.0,2021-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293032,8a802f603bf24515972b042d5902f724,8a802f603bf24515972b042d5902f724,39012,55,u,app,mobile,16.0,11.0,2.0,8.0,7.0,4.0,4.0,8.000000,0.0,0.0,13.316667,NaN,NaN,NaN,13.316667,0.0,NaN,2021-02-17
293033,8a802f603bf24515972b042d5902f724,8a802f603bf24515972b042d5902f724,39012,55,u,app,mobile,8.0,5.0,3.0,5.0,4.0,3.0,3.0,2.666667,0.0,0.0,0.966667,NaN,NaN,NaN,0.966667,0.0,NaN,2021-02-17
293034,748d27048ab946c4a32e5d96f557dbaf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293035,dd4d13dd95ff490bb9b60158c6a41b9c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293036,188074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
men_sus_nav[men_sus_nav['id_gigya'] == 'bb399b9372784e5189cf551b5029ce4f']

,cod_local,id_gigya,cod_postal,edad,genero,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
0,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,27.0,12.0,1.0,13.0,11.0,5.0,4.0,27.0,0.0,0.0,37.516667,0.0,0.0,0.037037,37.516667,0.0,0.0,2021-02-10
1,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,pc,28.0,13.0,2.0,7.0,7.0,3.0,3.0,14.0,0.0,0.0,8.858333,0.0,0.0,0.071429,8.858333,0.0,0.0,2021-02-08
2,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,13.0,7.0,1.0,8.0,6.0,6.0,4.0,13.0,0.0,0.0,18.966667,0.0,0.0,0.076923,18.966667,0.0,0.0,2021-02-06
3,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,32.0,17.0,1.0,17.0,16.0,8.0,7.0,32.0,0.0,0.0,45.366667,0.0,0.0,0.031250,45.366667,0.0,0.0,2021-01-24
4,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,13.0,7.0,1.0,6.0,5.0,5.0,4.0,13.0,0.0,0.0,21.483333,0.0,0.0,0.076923,21.483333,0.0,0.0,2021-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,pc,18.0,10.0,1.0,8.0,8.0,6.0,6.0,18.0,1.0,0.0,14.633333,0.0,0.0,0.055556,14.633333,0.0,0.0,2021-02-14
91,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,51,f,web,mobile,40.0,20.0,1.0,22.0,18.0,3.0,3.0,40.0,0.0,0.0,47.916667,0.0,0.0,0.025000,47.916667,0.0,0.0,2021-01-05
92,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,pc,30.0,16.0,1.0,12.0,12.0,5.0,5.0,30.0,1.0,0.0,21.950000,0.0,0.0,0.033333,21.950000,0.0,0.0,2021-02-13
93,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,51,f,web,pc,3.0,2.0,1.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.200000,0.0,0.0,0.333333,1.200000,0.0,0.0,2021-02-07
94,bb399b9372784e5189cf551b5029ce4f,bb399b9372784e5189cf551b5029ce4f,39011,52,f,web,mobile,34.0,15.0,1.0,15.0,14.0,6.0,5.0,34.0,0.0,0.0,65.366667,0.0,0.0,0.029412,65.366667,0.0,0.0,2021-02-04

In [ ]:
del men_sus_nav['cod_local']

In [73]:
del men_sus_nav['fecha_navegacion']

In [93]:
men_sus_nav.groupby(['id_gigya','cod_postal','edad','genero','tipo_navega','tipo_dispositivo'], as_index=False).sum()

,id_gigya,cod_postal,edad,genero,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados
0,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,1109.0,546.0,216.0,517.0,518.0,234.0,213.0,481.380952,0.0,0.0,525.422460,0.0,0.0,0.000000,521.905238,0.0,0.0
1,00216a84e17c4773be309083c7488425,39009,54,m,web,mobile,18.0,8.0,2.0,9.0,5.0,2.0,1.0,18.000000,0.0,0.0,39.966667,0.0,0.0,0.225000,39.966667,4.0,0.0
2,00216a84e17c4773be309083c7488425,39009,54,m,app,mobile,9.0,5.0,2.0,6.0,5.0,2.0,2.0,4.500000,0.0,0.0,6.100000,0.0,0.0,0.000000,6.025000,0.0,0.0
3,00216a84e17c4773be309083c7488425,39009,54,m,web,mobile,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.000000,0.0,1.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
4,00240e86543a4bd5bacb8f5a7b932ceb,39795,32,m,app,mobile,55.0,43.0,18.0,29.0,28.0,18.0,15.0,48.166667,0.0,0.0,45.458333,0.0,0.0,0.000000,45.125000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13506,fff729e8088d47a1ab74dcecdf5c3b77,94117,44,m,app,mobile,399.0,169.0,162.0,130.0,102.0,93.0,75.0,134.780952,0.0,0.0,215.580754,0.0,0.0,0.000000,215.580754,0.0,0.0
13507,fff729e8088d47a1ab74dcecdf5c3b77,94117,44,m,web,mobile,29.0,19.0,14.0,24.0,15.0,11.0,11.0,24.000000,0.0,3.0,35.066667,12.0,10.0,3.952381,35.075000,0.0,0.0
13508,fff729e8088d47a1ab74dcecdf5c3b77,94117,44,m,web,pc,135.0,80.0,58.0,53.0,38.0,36.0,28.0,73.850000,3.0,24.0,92.286667,0.0,0.0,8.716071,153.441667,0.0,0.0
13509,fff729e8088d47a1ab74dcecdf5c3b77,94117,44,m,app,mobile,18.0,4.0,4.0,6.0,2.0,5.0,1.0,4.500000,0.0,0.0,12.154167,0.0,0.0,0.000000,12.154167,0.0,0.0
13510,fff729e8088d47a1ab74dcecdf5c3b77,94117,44,m,web,mobile,12.0,7.0,7.0,12.0,7.0,7.0,7.0,8.500000,0.0,2.0,0.525000,6.0,6.0,2.000000,0.608333,0.0,0.0

In [80]:
men_sus_nav.groupby(['id_gigya'], as_index=False).sum()

,id_gigya,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,f,m,u,app,web,mobile,pc
0,00216a84e17c4773be309083c7488425,1137.0,560.0,221.0,533.0,529.0,238.0,216.0,504.880952,0.0,1.0,571.489127,0.0,0.0,0.225000,567.896905,4.0,0.0,0.0,71.0,0.0,68.0,3.0,71.0,0.0
1,00240e86543a4bd5bacb8f5a7b932ceb,341.0,214.0,124.0,162.0,137.0,68.0,62.0,212.866667,18.0,30.0,525.248056,18.0,16.0,17.889491,579.302778,0.0,0.0,0.0,75.0,0.0,14.0,61.0,43.0,32.0
2,005aaa540c874648a1e273872f88e7ab,1546.0,863.0,168.0,964.0,962.0,292.0,227.0,645.866667,0.0,2.0,1270.530556,0.0,0.0,0.125000,1265.633889,0.0,0.0,61.0,0.0,0.0,58.0,3.0,61.0,0.0
3,006968865c844a2e9316d9c086970630,1878.0,780.0,221.0,588.0,544.0,131.0,125.0,733.416667,65.0,17.0,625.048611,6.0,5.0,8.409980,657.777778,3.0,0.0,0.0,92.0,4.0,26.0,70.0,37.0,59.0
4,007e0c66c63d40d58f759659135b3321,759.0,451.0,143.0,439.0,331.0,84.0,71.0,348.150000,6.0,20.0,547.846944,1.0,1.0,12.393533,522.922500,0.0,57.0,0.0,0.0,61.0,0.0,61.0,61.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4029,ff9bcd67c19d4a819e5b91fbac56ea26,71.0,45.0,32.0,27.0,28.0,10.0,10.0,43.666667,0.0,0.0,96.811111,0.0,0.0,0.000000,96.661111,0.0,0.0,0.0,0.0,18.0,18.0,0.0,18.0,0.0
4030,ff9e4b3f569c4dbc927bfac33f881f29,872.0,500.0,115.0,301.0,296.0,72.0,65.0,704.833333,24.0,21.0,1582.597222,3.0,2.0,8.635908,1630.775000,0.0,0.0,0.0,0.0,88.0,15.0,73.0,35.0,53.0
4031,ffb227dce56b49b79bc255899cc3c485,510.0,237.0,187.0,148.0,117.0,61.0,43.0,196.940476,115.0,20.0,588.872778,0.0,0.0,7.745727,732.716389,0.0,0.0,0.0,70.0,0.0,39.0,31.0,39.0,31.0
4032,ffecb1105e7e43b193ba63cecdf5d5a6,1110.0,498.0,165.0,289.0,225.0,92.0,73.0,804.500000,9.0,51.0,1679.053611,14.0,12.0,15.904471,1814.438889,35.0,0.0,0.0,107.0,0.0,0.0,107.0,78.0,29.0
4033,fff729e8088d47a1ab74dcecdf5c3b77,594.0,280.0,246.0,225.0,164.0,152.0,122.0,246.630952,3.0,30.0,355.613254,18.0,16.0,14.668452,416.859921,0.0,0.0,0.0,107.0,1.0,55.0,53.0,73.0,35.0

In [67]:
users.users.groupby('id_gigya').agg(['count', 'sum'])

                                                  paginas_vistas        \
                                                           count   sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw              1     1
00216a84e17c4773be309083c7488425                              71  1137
00240e86543a4bd5bacb8f5a7b932ceb                              75   341
005aaa540c874648a1e273872f88e7ab                              61  1546
006968865c844a2e9316d9c086970630                              96  1878
...                                                          ...   ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                      1     2
prospect-554153                                                1    14
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                      1     9
prospect-cf3e57f2558f476481c85e389010988f                      1    16
prospect-e608e6dd66804947834d487671d64082                      1    20

                                                  contenidos      visitas  \
                                                       count  sum   count
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw          1    1       1
00216a84e17c4773be309083c7488425                          71  560      71
00240e86543a4bd5bacb8f5a7b932ceb                          75  214      75
005aaa540c874648a1e273872f88e7ab                          61  863      61
006968865c844a2e9316d9c086970630                          96  780      96
...                                                      ...  ...     ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                  1    1       1
prospect-554153                                            1    6       1
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                  1    3       1
prospect-cf3e57f2558f476481c85e389010988f                  1    7       1
prospect-e608e6dd66804947834d487671d64082                  1    9       1

                                                       pv_muro       \
                                                   sum   count  sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw    1       1    0
00216a84e17c4773be309083c7488425                   221      71  533
00240e86543a4bd5bacb8f5a7b932ceb                   124      75  162
005aaa540c874648a1e273872f88e7ab                   168      61  964
006968865c844a2e9316d9c086970630                   221      96  588
...                                                ...     ...  ...
prospect-4e182b5b9f7e42c8b95756e1559e8610            1       1    0
prospect-554153                                      3       1    3
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968            2       1    1
prospect-cf3e57f2558f476481c85e389010988f            7       1    5
prospect-e608e6dd66804947834d487671d64082            4       1    5

                                                  contenidos_muro       \
                                                            count  sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw               1    0
00216a84e17c4773be309083c7488425                               71  529
00240e86543a4bd5bacb8f5a7b932ceb                               75  137
005aaa540c874648a1e273872f88e7ab                               61  962
006968865c844a2e9316d9c086970630                               96  544
...                                                           ...  ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                       1    0
prospect-554153                                                 1    2
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                       1    1
prospect-cf3e57f2558f476481c85e389010988f                       1    5
prospect-e608e6dd66804947834d487671d64082                       1    4

                                                  pv_premium       \
                                                       count  sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw          1    0
00216a84e17c4773be309083c7488425                          71  238
00240e86543a4bd5bacb8f5a7b932ceb                          75   68
005aaa540c874648a1e273872f88e7ab                          61  292
006968865c844a2e9316d9c086970630                          96  131
...                                                      ...  ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                  1    0
prospect-554153                                            1    0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                  1    0
prospect-cf3e57f2558f476481c85e389010988f                  1    4
prospect-e608e6dd66804947834d487671d64082                  1    2

                                                  contenidos_premium       \
                                                               count  sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                  1    0
00216a84e17c4773be309083c7488425                                  71  216
00240e86543a4bd5bacb8f5a7b932ceb                                  75   62
005aaa540c874648a1e273872f88e7ab                                  61  227
006968865c844a2e9316d9c086970630                                  96  125
...                                                              ...  ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                          1    0
prospect-554153                                                    1    0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                          1    0
prospect-cf3e57f2558f476481c85e389010988f                          1    4
prospect-e608e6dd66804947834d487671d64082                          1    2

                                                  engagement              \
                                                       count         sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw          1    1.000000
00216a84e17c4773be309083c7488425                          71  504.880952
00240e86543a4bd5bacb8f5a7b932ceb                          75  212.866667
005aaa540c874648a1e273872f88e7ab                          61  645.866667
006968865c844a2e9316d9c086970630                          96  733.416667
...                                                      ...         ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                  1    2.000000
prospect-554153                                            1    4.666667
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                  1    4.500000
prospect-cf3e57f2558f476481c85e389010988f                  1    2.285714
prospect-e608e6dd66804947834d487671d64082                  1    5.000000

                                                  videos     rebotes      \
                                                   count sum   count sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw      1   0       1   1
00216a84e17c4773be309083c7488425                      71   0      71   1
00240e86543a4bd5bacb8f5a7b932ceb                      75  18      75  30
005aaa540c874648a1e273872f88e7ab                      61   0      61   2
006968865c844a2e9316d9c086970630                      96  65      96  17
...                                                  ...  ..     ...  ..
prospect-4e182b5b9f7e42c8b95756e1559e8610              1   0       1   0
prospect-554153                                        1   2       1   1
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968              1   0       1   0
prospect-cf3e57f2558f476481c85e389010988f              1   0       1   3
prospect-e608e6dd66804947834d487671d64082              1   0       1   1

                                                  tm_visita               \
                                                      count          sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw         0     0.000000
00216a84e17c4773be309083c7488425                         70   571.489127
00240e86543a4bd5bacb8f5a7b932ceb                         63   525.248056
005aaa540c874648a1e273872f88e7ab                         59  1270.530556
006968865c844a2e9316d9c086970630                         91   625.048611
...                                                     ...          ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                 1     0.666667
prospect-554153                                           1     9.077778
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                 1     1.016667
prospect-cf3e57f2558f476481c85e389010988f                 1     3.804762
prospect-e608e6dd66804947834d487671d64082                 1     1.587500

                                                  paginas_vistas_amp        \
                                                               count   sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                  1   0.0
00216a84e17c4773be309083c7488425                                   3   0.0
00240e86543a4bd5bacb8f5a7b932ceb                                  61  18.0
005aaa540c874648a1e273872f88e7ab                                   3   0.0
006968865c844a2e9316d9c086970630                                  70   6.0
...                                                              ...   ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                          1   0.0
prospect-554153                                                    1   0.0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                          1   0.0
prospect-cf3e57f2558f476481c85e389010988f                          1   0.0
prospect-e608e6dd66804947834d487671d64082                          1   0.0

                                                  visitas_amp        \
                                                        count   sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw           1   0.0
00216a84e17c4773be309083c7488425                            3   0.0
00240e86543a4bd5bacb8f5a7b932ceb                           61  16.0
005aaa540c874648a1e273872f88e7ab                            3   0.0
006968865c844a2e9316d9c086970630                           70   5.0
...                                                       ...   ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                   1   0.0
prospect-554153                                             1   0.0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                   1   0.0
prospect-cf3e57f2558f476481c85e389010988f                   1   0.0
prospect-e608e6dd66804947834d487671d64082                   1   0.0

                                                  engagement_sin_rebote  \
                                                                  count
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                     0
00216a84e17c4773be309083c7488425                                      2
00240e86543a4bd5bacb8f5a7b932ceb                                     51
005aaa540c874648a1e273872f88e7ab                                      1
006968865c844a2e9316d9c086970630                                     65
...                                                                 ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                             1
prospect-554153                                                       1
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                             1
prospect-cf3e57f2558f476481c85e389010988f                             1
prospect-e608e6dd66804947834d487671d64082                             1

                                                              \
                                                         sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw   0.000000
00216a84e17c4773be309083c7488425                    0.225000
00240e86543a4bd5bacb8f5a7b932ceb                   17.889491
005aaa540c874648a1e273872f88e7ab                    0.125000
006968865c844a2e9316d9c086970630                    8.409980
...                                                      ...
prospect-4e182b5b9f7e42c8b95756e1559e8610           0.500000
prospect-554153                                     0.153846
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968           0.222222
prospect-cf3e57f2558f476481c85e389010988f           0.307692
prospect-e608e6dd66804947834d487671d64082           0.157895

                                                  tm_visita_sin_rebote  \
                                                                 count
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                    0
00216a84e17c4773be309083c7488425                                    70
00240e86543a4bd5bacb8f5a7b932ceb                                    62
005aaa540c874648a1e273872f88e7ab                                    58
006968865c844a2e9316d9c086970630                                    91
...                                                                ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                            1
prospect-554153                                                      1
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                            1
prospect-cf3e57f2558f476481c85e389010988f                            1
prospect-e608e6dd66804947834d487671d64082                            1

                                                                \
                                                           sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw     0.000000
00216a84e17c4773be309083c7488425                    567.896905
00240e86543a4bd5bacb8f5a7b932ceb                    579.302778
005aaa540c874648a1e273872f88e7ab                   1265.633889
006968865c844a2e9316d9c086970630                    657.777778
...                                                        ...
prospect-4e182b5b9f7e42c8b95756e1559e8610             0.666667
prospect-554153                                      13.266667
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968             1.016667
prospect-cf3e57f2558f476481c85e389010988f             6.658333
prospect-e608e6dd66804947834d487671d64082             1.988889

                                                  n_salta_metered      \
                                                            count sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw               1   0
00216a84e17c4773be309083c7488425                               71   4
00240e86543a4bd5bacb8f5a7b932ceb                               75   0
005aaa540c874648a1e273872f88e7ab                               61   0
006968865c844a2e9316d9c086970630                               96   3
...                                                           ...  ..
prospect-4e182b5b9f7e42c8b95756e1559e8610                       1   0
prospect-554153                                                 1   0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                       1   0
prospect-cf3e57f2558f476481c85e389010988f                       1   0
prospect-e608e6dd66804947834d487671d64082                       1   1

                                                  n_comentarios_enviados       \
                                                                   count  sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                      1  0.0
00216a84e17c4773be309083c7488425                                       3  0.0
00240e86543a4bd5bacb8f5a7b932ceb                                      61  0.0
005aaa540c874648a1e273872f88e7ab                                       3  0.0
006968865c844a2e9316d9c086970630                                      70  0.0
...                                                                  ...  ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                              1  0.0
prospect-554153                                                        1  0.0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                              1  0.0
prospect-cf3e57f2558f476481c85e389010988f                              1  0.0
prospect-e608e6dd66804947834d487671d64082                              1  0.0

                                                  fecha_navegacion  \
                                                             count
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                1
00216a84e17c4773be309083c7488425                                71
00240e86543a4bd5bacb8f5a7b932ceb                                75
005aaa540c874648a1e273872f88e7ab                                61
006968865c844a2e9316d9c086970630                                96
...                                                            ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                        1
prospect-554153                                                  1
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                        1
prospect-cf3e57f2558f476481c85e389010988f                        1
prospect-e608e6dd66804947834d487671d64082                        1

                                                                                                      \
                                                                                                 sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw                                         2021-01-18
00216a84e17c4773be309083c7488425                   2021-02-082021-02-122021-02-222021-02-032021-0...
00240e86543a4bd5bacb8f5a7b932ceb                   2021-01-172021-02-092021-01-052021-02-122021-0...
005aaa540c874648a1e273872f88e7ab                   2021-02-082021-02-122021-02-222021-02-032021-0...
006968865c844a2e9316d9c086970630                   2021-01-272021-02-212021-01-212021-01-242021-0...
...                                                                                              ...
prospect-4e182b5b9f7e42c8b95756e1559e8610                                                 2021-02-01
prospect-554153                                                                           2021-02-06
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968                                                 2021-02-04
prospect-cf3e57f2558f476481c85e389010988f                                                 2021-02-17
prospect-e608e6dd66804947834d487671d64082                                                 2021-01-22

                                                      f           m        \
                                                  count   sum count   sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw     1   0.0     1   0.0
00216a84e17c4773be309083c7488425                     71   0.0    71  71.0
00240e86543a4bd5bacb8f5a7b932ceb                     75   0.0    75  75.0
005aaa540c874648a1e273872f88e7ab                     61  61.0    61   0.0
006968865c844a2e9316d9c086970630                     96   0.0    96  92.0
...                                                 ...   ...   ...   ...
prospect-4e182b5b9f7e42c8b95756e1559e8610             1   0.0     1   1.0
prospect-554153                                       1   0.0     1   1.0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968             1   0.0     1   0.0
prospect-cf3e57f2558f476481c85e389010988f             1   0.0     1   1.0
prospect-e608e6dd66804947834d487671d64082             1   0.0     1   0.0

                                                      u        app        \
                                                  count  sum count   sum
id_gigya
-guid-wvcd8fl0syyvam576eo1m9ly7wfenrzvsongfjygpvw     1  1.0     1   0.0
00216a84e17c4773be309083c7488425                     71  0.0    71  68.0
00240e86543a4bd5bacb8f5a7b932ceb                     75  0.0    75  14.0
005aaa540c874648a1e273872f88e7ab                     61  0.0    61  58.0
006968865c844a2e9316d9c086970630                     96  4.0    96  26.0
...                                                 ...  ...   ...   ...
prospect-4e182b5b9f7e42c8b95756e1559e8610             1  0.0     1   0.0
prospect-554153                                       1  0.0     1   0.0
prospect-97e1b3f3c1c8407d9fe8d97ec3f1b968             1  1.0     1   0.0
prospect-cf3e57f2558f476481c85e389010988f             1  0.0     1   0.0
prospect-e608e6dd66804947834d487671d64082             1  1.0     1   0.0


In [64]:
users.users

,id_gigya,cod_postal,edad,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion,f,m,u,app,web,mobile,pc
0,9f4f3c63575f4c119dd3197f7cbc2001,39609,NaN,1,1,1,0,0,0,0,1.000000,0,0,NaN,0.0,0.0,1.000000,NaN,0,0.0,2021-02-10,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1,670a42d953b64b6e85af13a97031634d,39120,NaN,3,2,1,1,1,1,1,3.000000,0,0,1.550000,0.0,0.0,0.333333,1.550000,0,0.0,2021-02-10,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,4ba048e82344496bb42210c94ebc9fde,39478,38,7,3,4,2,2,1,1,1.750000,0,3,0.991667,0.0,0.0,0.250000,3.966667,0,0.0,2021-02-10,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,757916,39350,30,13,7,1,7,4,3,1,13.000000,0,0,24.000000,0.0,0.0,0.076923,24.000000,0,0.0,2021-02-10,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,85beb7e84e634ea3b9134e809c53aaf6,39618,56,115,7,3,90,6,0,0,38.333333,0,0,443.283333,0.0,0.0,0.026087,443.283333,0,0.0,2021-02-10,0.0,1.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377787,c72121c614754f9ba420a651ebae45ef,39006,58,1,1,1,1,1,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-26,0.0,1.0,0.0,0.0,1.0,1.0,0.0
377788,031cf4a3aa3641e38efa70f655a0ee25,39003,55,11,4,2,3,3,1,1,5.500000,1,0,32.691667,0.0,0.0,0.181818,32.133333,0,0.0,2021-01-26,0.0,1.0,0.0,0.0,1.0,0.0,1.0
377789,874a187a51ae48079758a88182e22ce1,39300,42,2,1,2,0,0,0,0,1.000000,0,2,NaN,0.0,0.0,NaN,NaN,0,0.0,2021-01-26,0.0,1.0,0.0,0.0,1.0,1.0,0.0
377790,db3b4f858e2c408aa06b967ec01d8eb6,39002,58,21,9,2,9,6,1,1,10.500000,0,0,26.008333,0.0,0.0,0.095238,26.008333,1,0.0,2021-01-26,0.0,0.0,1.0,0.0,1.0,1.0,0.0
377791,641748,39008,36,11,6,3,3,2,0,0,3.666667,0,1,8.300000,0.0,0.0,0.200000,12.450000,1,0.0,2021-01-26,1.0,0.0,0.0,0.0,1.0,0.0,1.0