# ANÁLISIS DE DATOS POR FICHERO

In [39]:
import pandas as pd
import numpy as np

In [40]:
pd.options.display.max_columns = None
pd.options.mode.chained_assignment = None

## ANÁLISIS DE SUSCRIPCIONES

In [319]:
suscriptions_file = '../data/suscripciones.csv'
suscriptions = pd.read_csv(suscriptions_file, parse_dates = ['fecha_creacion', 'fecha_modificacion', 'fecha_inicio', 'fecha_fin'], 
                           dtype = {'id_producto' : 'object', 'id_suscripcion_original' : 'object', 'id_suscripcion' : 'object'})
suscriptions

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,NaN,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,NaN,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,NaN,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,NaN,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,upgrade,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,upgrade,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,NaN,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,NaN,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,NaN,NaN

In [320]:
suscriptions.shape

(10951, 13)

In [315]:
suscriptions.isna().sum().sort_values(ascending = False)

id_suscripcion_original    10101
transicion                 10101
id_producto                   61
referencia_producto           61
fecha_fin                      0
fecha_inicio                   0
fecha_modificacion             0
fecha_creacion                 0
autorenovable                  0
periodicidad                   0
estado_suscripcion             0
id_suscripcion                 0
cod_local                      0
dtype: int64

In [318]:
suscriptions.dtypes

cod_local                          object
id_suscripcion                     object
estado_suscripcion                 object
periodicidad                       object
referencia_producto                object
id_producto                        object
autorenovable                        bool
fecha_creacion             datetime64[ns]
fecha_modificacion         datetime64[ns]
fecha_inicio               datetime64[ns]
fecha_fin                  datetime64[ns]
transicion                        float64
id_suscripcion_original            object
dtype: object

In [324]:
suscriptions['referencia_producto'].value_counts()

pack-on-diariomontanes                                             3026
pack-on-diariomontanes-anual                                       1163
suscripcion-on-eldiariomontanes-primermesgratis                     854
pack-on-2-meses-gratis-eldiariomontanes                             720
pack-on-diariomontanes-anual-2020                                   657
pack-on-diariomontanes-primer-mes-1-euro-verano-2020                605
pack-on-diariomontanes-OFERTA VERANO                                590
SUSCRIPCIÓN- EL DIARIO MONTAÑÉS 4º aniversario                      507
pack-on-diariomontanes-dos-meses-tercer-aniversario                 338
3mxe-3moferta-on-3m-cap-30d-201120-EDIA                             334
2m1e-4anivers-on-1m-cap-1d-210202-EDIA                              186
suscripcion-on-diariomontanes-trimestral-noviembre-promoción-20     156
pack-on-anual-tucocinatradicional                                   149
pack-on-anual-tucocinatradicional-diciembre                         121
suscripcion-on-diariomontanes-blackfriday-20                        120
pack-on-diariomontanes-primermesgratis                              109
pack-on-anual-octubre19                                             103
pack-navega-diariomontanes                                           98
suscripcion-anual-on-cartera-balenciaga                              94
suscripcion-anual-on-productoslupa                                   90
pack-on-diariomontanes-dos meses 1 €                                 87
on-plus-diciembre-2017                                               86
nop--on-1m-noa-170123-EDIA                                           84
reg-cocinatrad-on-12m-cap-30d-201204-EDIA                            70
pack-on-blackfriday-2019                                             61
on-plus-febrero-2018                                                 54
suscripcion-on-diariomontanes-trimestral-20                          51
pack-on-diariomontanes-primer mes 1 euro-verano 2020                 50
nop--on-3m-noa-a-200416-EDIA                                         49
nop--on-12m-noa-a-181219-EDIA                                        30
nop--on-12m-noa-200921-EDIA                                          30
pack-on-diariomontanes-septiembre                                    28
on-plus-mayo-2018                                                    24
pack-on-diariomontanes-promo-abril                                   19
on-plus-abril-2018                                                   19
on-plus-semana-santa-2018                                            16
on-plus-noviembre-2017                                               13
pack-total-7-diariomontanes                                          12
pack-on-diariomontanes-anual-2020 2.0                                10
pack-ondiariomontanes-promo-junio-2                                   9
SUSCRIPCIÓN  EL Diario Montañés on+                                   9
pack-on-1mesgratis-captacion-rtim-diariomontañes                      8
on-plus-junio-2018                                                    8
nop--nav-1m-noa-170123-EDIA                                           6
pack-on-eldiariomontanes-3meses                                       6
nop-trimestral-on-3m-noa--201203-EDIA                                 6
pack-on-diariomontanes-anual-SCIF                                     5
pack-on-eldiariomontanes-anual-promo                                  4
nop--tot-1m-noa-170131-EDIA                                           4
nop-retencion-on-12m-rec-a-200219-EDIA                                3
pack-on-eldiariomontanes-anual 29,95€                                 3
3mxe-3moferta-on-3m-cap-30d-080121-ECOM                               2
pack-on-anual-retencion                                               2
reg-tjtaeci15-on-12m-cap--210226-EDIA                                 1
pack-ondiariomontanes-promo-junio                                     1
Name: referencia_producto, dtype: int64

In [325]:
suscriptions['cod_local'].value_counts()

d22a5f549dbb4738bb243a1031c381be                      13
b78d22bcb585412da99467f1410e8be0                      12
_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0Bzy4=     8
934909fdf0f64e92b8f2d5f19d43bccf                       8
806730                                                 8
                                                      ..
e63f3bed31e14f0abc5cf8439183c039                       1
39275                                                  1
05392a3c3ddd41679c5e33709eb8bab8                       1
305216                                                 1
1a85b2f5789042f5bf9c873f8772c248                       1
Name: cod_local, Length: 8326, dtype: int64

In [326]:
suscriptions[suscriptions['cod_local'] == '950e805fb31d4633b84c1001ed7a018d'].sort_values('fecha_fin')

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
7599,950e805fb31d4633b84c1001ed7a018d,10538,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 15:56:44,2019-12-26 15:05:47,2017-03-08,2019-12-26,0,NaN
6941,950e805fb31d4633b84c1001ed7a018d,46900,canceled,Anual,pack-on-diariomontanes,90721,True,2019-12-26 14:04:17,2020-12-30 07:00:13,2019-12-26,2020-12-30,1,10538
10384,950e805fb31d4633b84c1001ed7a018d,36007932,canceled,Trimestral,nop--on-3m-noa-a-200416-EDIA,98924,True,2021-01-06 22:46:28,2021-01-07 15:19:56,2021-01-06,2021-01-07,0,NaN
6658,950e805fb31d4633b84c1001ed7a018d,36008029,active,Anual,nop--on-12m-noa-200921-EDIA,100426,True,2021-01-07 15:20:00,2021-01-07 15:20:00,2021-01-07,2022-01-06,1,36007932

In [327]:
suscriptions[suscriptions['estado_suscripcion'] == 'canceled']['periodicidad'].value_counts()

Mensual       4645
Anual          430
Trimestral      71
Name: periodicidad, dtype: int64

In [328]:
suscriptions.groupby('periodicidad')['referencia_producto'].count()

periodicidad
Anual         2735
Mensual       7557
Trimestral     598
Name: referencia_producto, dtype: int64

In [330]:
suscriptions['fecha_fin'] - suscriptions['fecha_inicio']

0       1488 days
1        531 days
2       1460 days
3       1406 days
4        623 days
           ...
10946    364 days
10947    364 days
10948     96 days
10949    180 days
10950    178 days
Length: 10951, dtype: timedelta64[ns]

In [331]:
suscriptions =  suscriptions[(suscriptions['fecha_fin'] >= suscriptions['fecha_inicio'])]

In [332]:
suscriptions

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,0,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,0,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,0,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,0,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,1,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,1,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,0,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,0,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,0,NaN

In [41]:
from subscriptions import Subscriptions

In [42]:
sus = Subscriptions(data_root="../data/")
sus.set_data()

In [43]:
sus.get_data()

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_original
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,NaN,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,NaN,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,NaN,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,NaN,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,upgrade,74366
10947,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,upgrade,38254
10948,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,NaN,NaN
10949,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,NaN,NaN
10950,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,NaN,NaN

In [44]:
sus.clean_data()

In [45]:
sus.get_data()

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
0,bb399b9372784e5189cf551b5029ce4f,10119,active,Mensual,pack-on-diariomontanes,82063,True,2017-02-19 19:45:46,2021-02-16 05:03:50,2017-02-19,2021-03-18,False,NaN
1,bad5a9ea94cd4da0befc92e5d1b8a749,10537,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-08 14:19:56,2018-08-22 06:55:10,2017-03-08,2018-08-21,False,NaN
2,b6d8b038649b4158a4150ea6953b15ab,10569,active,Mensual,pack-on-diariomontanes,82063,True,2017-03-09 11:41:23,2021-02-06 05:04:47,2017-03-09,2021-03-08,False,NaN
3,2665f56bbe5842ca8bcaba17d0abd77f,10750,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-14 12:48:31,2021-01-18 07:00:04,2017-03-14,2021-01-18,False,NaN
4,af02dac14a454e85a0f857781cb9d7a4,10847,canceled,Mensual,pack-on-diariomontanes,82063,True,2017-03-17 21:30:16,2018-12-01 07:55:22,2017-03-17,2018-11-30,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10938,fdd81fc7f4d74c19b2b771a38ce4d37e,83294,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-10 15:38:59,2020-10-10 15:42:55,2020-10-10,2021-10-09,False,NaN
10939,ece8c1708a914808a0322f8047a0dc8a,85315,active,Anual,pack-on-diariomontanes-anual-2020,100426,True,2020-10-20 19:40:44,2020-10-20 19:48:16,2020-10-20,2021-10-19,False,NaN
10940,1cebde9c62784f79a27216562942d1f5,86521,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-10-29 21:23:15,2021-02-02 07:00:20,2020-10-29,2021-02-02,False,NaN
10941,4dc64b016741482dab474a50b4e803be,87929,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-11-12 11:11:44,2021-02-09 05:00:50,2020-11-12,2021-05-11,False,NaN
10942,d7087e42acb949dc8200d496ec897c4c,89194,active,Trimestral,suscripcion-on-diariomontanes-trimestral-novie...,100551,True,2020-12-01 19:52:34,2021-02-26 05:01:59,2020-12-01,2021-05-28,False,NaN

In [47]:
for c in sus.subscriptions.columns:
    if (len(sus.subscriptions[c].isna().value_counts()) > 1):
        print (c)
        print (sus.subscriptions[c].isna().value_counts())

referencia_producto
False    10882
True        61
Name: referencia_producto, dtype: int64
id_producto
False    10882
True        61
Name: id_producto, dtype: int64
id_suscripcion_final
True     10093
False      850
Name: id_suscripcion_final, dtype: int64

In [55]:
sus.subscriptions[sus.subscriptions['referencia_producto'].isna()]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
23,f3756dfa44b34c21895c5915e933e7f1,21935,canceled,Mensual,NaN,NaN,True,2018-12-12 11:03:58,2018-12-12 11:03:58,2018-12-12,2019-01-11,False,NaN
209,_guid_W6mm5UqUkI9e-Zp2lgtbFbXyEjTFTB7ojAWRyaob...,10566,active,Mensual,NaN,NaN,True,2017-03-09 10:39:42,2017-03-09 10:39:42,2017-03-09,2017-04-08,False,NaN
366,_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0B...,10438,active,Mensual,NaN,NaN,True,2017-03-05 14:19:09,2017-03-05 14:19:09,2017-03-05,2017-04-04,False,NaN
570,d22a5f549dbb4738bb243a1031c381be,27139,active,Mensual,NaN,NaN,True,2019-02-24 19:31:48,2019-02-24 19:31:48,2019-02-24,2019-03-23,False,NaN
885,0bf1ec92ceec4019be58bf069633f5f8,10252,active,Mensual,NaN,NaN,True,2017-02-28 09:02:19,2017-02-28 09:02:19,2017-02-28,2017-03-27,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9332,7135774db94941ee8c7500bd6872b7e0,12192,active,Mensual,NaN,NaN,True,2017-07-01 20:00:21,2017-07-01 20:00:21,2017-07-01,2017-07-31,False,NaN
9447,_guid_JT5ACldDClD0TQhkVyETqg6QhmfQUEOzjQvwad0B...,10335,canceled,Mensual,NaN,NaN,True,2017-03-02 10:52:18,2017-03-02 10:52:18,2017-03-02,2017-04-01,False,NaN
10303,c976509f263641a197f1942fa5f9e790,11353,active,Mensual,NaN,NaN,True,2017-04-17 15:20:58,2017-04-17 15:20:58,2017-04-17,2017-05-16,False,NaN
10306,7135774db94941ee8c7500bd6872b7e0,12196,active,Mensual,NaN,NaN,True,2017-07-01 20:14:37,2017-07-01 20:14:37,2017-07-01,2017-07-31,False,NaN
10531,d22a5f549dbb4738bb243a1031c381be,27135,active,Anual,NaN,NaN,True,2019-02-24 19:26:42,2019-02-24 19:26:42,2019-02-24,2020-02-23,False,NaN

In [58]:
sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual']['referencia_producto'].value_counts()

pack-on-diariomontanes                                  2823
suscripcion-on-eldiariomontanes-primermesgratis          854
pack-on-2-meses-gratis-eldiariomontanes                  720
pack-on-diariomontanes-primer-mes-1-euro-verano-2020     605
pack-on-diariomontanes-OFERTA VERANO                     590
SUSCRIPCIÓN- EL DIARIO MONTAÑÉS 4º aniversario           507
pack-on-diariomontanes-dos-meses-tercer-aniversario      338
2m1e-4anivers-on-1m-cap-1d-210202-EDIA                   186
suscripcion-on-diariomontanes-blackfriday-20             120
pack-on-diariomontanes-primermesgratis                   109
pack-navega-diariomontanes                                98
pack-on-diariomontanes-dos meses 1 €                      87
on-plus-diciembre-2017                                    86
nop--on-1m-noa-170123-EDIA                                84
pack-on-blackfriday-2019                                  61
on-plus-febrero-2018                                      54
pack-on-diariomontanes-primer mes 1 euro-verano 2020      50
pack-on-diariomontanes-septiembre                         28
on-plus-mayo-2018                                         23
pack-on-diariomontanes-promo-abril                        19
on-plus-abril-2018                                        17
on-plus-semana-santa-2018                                 16
on-plus-noviembre-2017                                    13
pack-ondiariomontanes-promo-junio-2                        9
on-plus-junio-2018                                         8
SUSCRIPCIÓN  EL Diario Montañés on+                        8
pack-on-1mesgratis-captacion-rtim-diariomontañes           8
nop--nav-1m-noa-170123-EDIA                                6
pack-on-eldiariomontanes-3meses                            6
pack-on-eldiariomontanes-anual-promo                       4
nop--tot-1m-noa-170131-EDIA                                4
pack-total-7-diariomontanes                                4
pack-on-eldiariomontanes-anual 29,95€                      3
pack-ondiariomontanes-promo-junio                          1
Name: referencia_producto, dtype: int64

In [61]:
sus.subscriptions[(sus.subscriptions['fecha_creacion'] < sus.subscriptions['fecha_creacion'])]

Empty DataFrame
Columns: [cod_local, id_suscripcion, estado_suscripcion, periodicidad, referencia_producto, id_producto, autorenovable, fecha_creacion, fecha_modificacion, fecha_inicio, fecha_fin, transicion, id_suscripcion_final]
Index: []

In [45]:
sus.subscriptions[sus.subscriptions['transicion'] == True].groupby('periodicidad').count()

,cod_local,id_suscripcion,estado_suscripcion,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
periodicidad,,,,,,,,,,,,
Anual,17,17,17,17,17,17,17,17,17,17,17,17
Mensual,831,831,831,831,831,831,831,831,831,831,831,831
Trimestral,2,2,2,2,2,2,2,2,2,2,2,2

In [46]:
sus.subscriptions[(sus.subscriptions['periodicidad'] == 'Trimestral') & (sus.subscriptions['transicion'] == True)]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
1649,_guid_jeMYYUxd7QZmr6Y_IJsHzWu_7zQruabGV5SgLXY7...,87245,canceled,Trimestral,suscripcion-on-diariomontanes-trimestral-20,98924,True,2020-11-06 01:02:56,2021-01-24 13:13:47,2020-11-06,2021-01-24,True,36012160
10377,950e805fb31d4633b84c1001ed7a018d,36007932,canceled,Trimestral,nop--on-3m-noa-a-200416-EDIA,98924,True,2021-01-06 22:46:28,2021-01-07 15:19:56,2021-01-06,2021-01-07,True,36008029

In [47]:
#36012160 Trimestral
sus.subscriptions[sus.subscriptions['id_suscripcion'] == '36008029']

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
6655,950e805fb31d4633b84c1001ed7a018d,36008029,active,Anual,nop--on-12m-noa-200921-EDIA,100426,True,2021-01-07 15:20:00,2021-01-07 15:20:00,2021-01-07,2022-01-06,False,NaN

In [48]:
sus.subscriptions[(sus.subscriptions['periodicidad'] == 'Anual') & (sus.subscriptions['transicion'] == True)]

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
224,8d46c66a683b4457adf360246ddec545,24864,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-23 13:00:36,2021-01-23 17:23:56,2019-01-23,2021-01-23,True,36011879
619,d58f2a6078b64f9d805409b7bec50db1,23235,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-02 11:49:39,2019-12-31 12:47:19,2019-01-02,2019-12-31,True,47206
3177,22ac6346cb2540d1b134254335e9678e,43114,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-08 11:40:05,2020-10-21 11:03:43,2019-11-08,2020-10-21,True,85366
3295,ae0868be502f482689679633ff725069,42990,canceled,Anual,pack-on-anual-octubre19,94652,False,2019-11-05 12:42:49,2020-11-01 10:06:12,2019-11-05,2020-11-01,True,86731
4149,57128,22824,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2018-12-26 09:50:00,2020-12-23 15:40:28,2018-12-26,2020-12-23,True,36005826
5112,c8cc576e827a473fbe37103213b5a9b3,42909,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-04 13:51:51,2020-10-26 11:14:23,2019-11-04,2020-10-26,True,85976
5282,aa0a4d74d53141bd9e9dca12f9548280,50658,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2020-02-24 12:48:33,2021-02-22 15:40:34,2020-02-24,2021-02-22,True,36019242
5653,75d6665a5b8c4e5eb5ae584bb6ab2af9,27579,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-03-02 06:38:00,2021-02-28 18:30:01,2019-03-02,2021-02-28,True,36020399
5830,3a9f25eddcf6459aa162b15121229b2a,43037,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-06 13:08:27,2020-11-04 15:59:07,2019-11-06,2020-11-04,True,87013
6766,120175,43898,canceled,Anual,pack-on-anual-octubre19,94652,False,2019-11-21 11:10:12,2020-11-18 12:19:44,2019-11-21,2020-11-18,True,88454
7252,75c6024ffdb04df9ae63f2529d15ccd6,44084,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-22 18:27:12,2020-11-04 18:46:24,2019-11-22,2020-11-04,True,87022
8404,087dd0151ea446fc90f85046f796c0ea,23551,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2019-01-07 09:19:52,2020-01-01 18:28:49,2019-01-07,2020-01-01,True,47279
9029,4c0601916fd241daabae48d9534161c1,43476,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-18 11:02:52,2020-11-11 08:59:31,2019-11-18,2020-11-11,True,87824
9082,29468fd5dd194faab23a1318b196c4ea,42928,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-04 17:53:19,2020-11-02 11:28:20,2019-11-04,2020-11-02,True,86823
9422,33f17937c3b549ff8f7788442579a5d9,43471,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-18 09:51:52,2020-11-12 09:30:32,2019-11-18,2020-11-12,True,87907
9779,3f7ec2ee6ec64621bc01f6bc87b1ed8f,50937,canceled,Anual,pack-on-diariomontanes-anual,90721,True,2020-02-26 10:23:10,2021-02-09 16:23:09,2020-02-26,2021-02-09,True,36016701
10748,1ab9f37e6c4e4f6085c306d94409f005,44551,canceled,Anual,pack-on-anual-octubre19,94652,True,2019-11-26 12:43:05,2020-11-23 08:03:11,2019-11-26,2020-11-23,True,88812

In [49]:
# Anual 
sus.subscriptions[sus.subscriptions['id_suscripcion'] == '87824']

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,transicion,id_suscripcion_final
2196,4c0601916fd241daabae48d9534161c1,87824,active,Anual,pack-on-diariomontanes-anual-2020 2.0,100491,True,2020-11-11 07:54:16,2020-12-23 14:00:00,2020-11-11,2021-11-10,False,NaN

In [50]:
# Solo mensuales 
sus.subscriptions[sus.subscriptions['periodicidad'] == 'Mensual'].groupby('transicion').count()

,cod_local,id_suscripcion,estado_suscripcion,periodicidad,referencia_producto,id_producto,autorenovable,fecha_creacion,fecha_modificacion,fecha_inicio,fecha_fin,id_suscripcion_final
transicion,,,,,,,,,,,,
False,6766,6766,6766,6766,6718,6718,6766,6766,6766,6766,6766,0
True,831,831,831,831,831,831,831,831,831,831,831,831

## ANÁLISIS DE INDICADORES DE USUARIO

In [3]:
users_file = '../data/dm_indicadores_usuario.csv'
users = pd.read_csv(users_file)
users

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
0,78417469351791975736169845891825711610,75535567505083556960762774790239330639,006968865c844a2e9316d9c086970630,39310,33.0,m,anonimo,web,mobile,2,2,2,2,2,0,0,1.000000,0,2,NaN,2.0,2.0,NaN,NaN,0,0.0,2020-06-01
1,52425750985802126442668436210298346684,16451832170087691251533166194581228111,006968865c844a2e9316d9c086970630,39310,33.0,m,suscriptor,web,mobile,1,1,1,0,0,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2020-06-01
2,45307505850961913832102651929863475916,00428307531488269410201290079250673864,006968865c844a2e9316d9c086970630,39310,33.0,m,suscriptor,web,pc,28,12,3,8,8,0,0,9.333333,3,0,9.261111,0.0,0.0,0.107143,9.261111,0,0.0,2020-06-01
3,33997985857765348904611693873583459292,63017210247913765581302871108862417773,009875f699314f598cedd75d588bfbbe,39004,43.0,NaN,suscriptor,web,mobile,7,4,1,6,3,0,0,7.000000,0,0,5.216667,0.0,0.0,0.142857,5.216667,0,0.0,2020-06-01
4,81296065445598473884383853852904739808,36203010557659682852636129438578529630,00a488b7424641c683cd665375ba0838,39540,75.0,m,suscriptor,web,pc,69,29,1,21,12,2,2,69.000000,1,0,48.550000,0.0,0.0,0.014493,48.550000,0,0.0,2020-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,17820994817216648438804946554425008355,44495317034553139352426147463302322716,a0c2df0a9d8442abb1dd69bb41187dc9,39610,38.0,u,registrado,web,mobile,38,7,2,0,0,0,0,19.000000,0,1,53.841667,0.0,0.0,0.027027,107.683333,0,0.0,2020-06-01
996,11811022866339183337792737204324697793,37040961244367417731553356128723336342,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,m,suscriptor,web,mobile,13,1,6,0,0,0,0,2.166667,0,2,9.805556,0.0,0.0,0.363636,14.708333,0,0.0,2020-06-01
997,6239321634259109655492988748579986367,15515126231343402701698194286031773275,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,m,suscriptor,web,pc,3,1,1,0,0,0,0,3.000000,0,0,30.550000,0.0,0.0,0.333333,30.550000,0,0.0,2020-06-01
998,32702980139170587786917530168491791173,NaN,a13b758bd8e34e1d910ef3166fc0c849,28020,76.0,masculino,registrado,app,mobile,2,1,1,0,0,0,0,2.000000,0,0,0.600000,NaN,NaN,NaN,0.600000,0,NaN,2020-06-01
999,7196986871911805005198212641853412597,19100380572136867181619132953201971649,a17cf964c6a94ee8966e01cf79afb838,39011,35.0,f,suscriptor,web,mobile,3,2,2,0,0,0,0,1.500000,0,1,0.375000,0.0,0.0,0.500000,0.750000,0,0.0,2020-06-01

In [4]:
users['id_gigya'].value_counts()

07585fdfdcef4852a360959f001de726    6
5b2968a841bb461295620b578dd45b44    5
590691                              5
8d6bdca7147b4a5c96e66160d651d065    5
241066b0eaa24d9580310b1f5d6c726a    5
                                   ..
33a27b5ce59b4815afa6a41a12c75734    1
139966                              1
48317364e1644c289806d99269c24246    1
1520d585f551428cbfbee189e257703e    1
795166                              1
Name: id_gigya, Length: 698, dtype: int64

In [5]:
users[users['id_gigya'] == '590691']

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
598,60750559857167409865798252709514189125,84276174721453205262340849686860516320,590691,39012,44.0,m,suscriptor,web,pc,9,5,2,1,1,0,0,4.5,0,0,0.650000,0.0,0.0,0.222222,0.650000,0,0.0,2020-06-01
599,257236134474202137955052644960729265,37218332141971247492206460260620077656,590691,39012,44.0,m,registrado,web,pc,6,5,1,0,0,0,0,6.0,0,0,293.183333,0.0,0.0,0.166667,293.183333,0,0.0,2020-06-01
600,33589375103171956896917530303246482058,NaN,590691,39012,44.0,masculino,suscriptor,app,mobile,14,10,4,10,12,0,0,3.5,0,0,1.737500,NaN,NaN,NaN,1.708333,0,NaN,2020-06-01
601,257236134474202137955052644960729265,37218332141971247492206460260620077656,590691,39012,44.0,m,suscriptor,web,pc,153,12,2,98,8,0,0,76.5,1,0,381.800000,0.0,0.0,0.013072,381.716667,0,0.0,2020-06-01
602,35079765774944086424885195769904607809,69060259757641523212015816201729857196,590691,39012,44.0,m,registrado,web,mobile,1,1,1,0,0,0,0,1.0,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2020-06-01

In [6]:
suscriptions[suscriptions['cod_local'] == '590691']

NameError: name 'suscriptions' is not defined

In [7]:
users.columns

Index(['usuario', 'cookie', 'id_gigya', 'cod_postal', 'edad', 'genero',
       'tipo_login', 'tipo_navega', 'tipo_dispositivo', 'paginas_vistas',
       'contenidos', 'visitas', 'pv_muro', 'contenidos_muro', 'pv_premium',
       'contenidos_premium', 'engagement', 'videos', 'rebotes', 'tm_visita',
       'paginas_vistas_amp', 'visitas_amp', 'engagement_sin_rebote',
       'tm_visita_sin_rebote', 'n_salta_metered', 'n_comentarios_enviados',
       'fecha_navegacion'],
      dtype='object')

In [8]:
cols_agruped_by = users.columns[2:7] 
cols_agruped_by

Index(['id_gigya', 'cod_postal', 'edad', 'genero', 'tipo_login'], dtype='object')

In [9]:
cols_agruped_by = cols_agruped_by.insert(0,'fecha_navegacion')
cols_agruped_by

Index(['fecha_navegacion', 'id_gigya', 'cod_postal', 'edad', 'genero',
       'tipo_login'],
      dtype='object')

In [10]:
data_cols_agruped = users.columns[9:-1]
data_cols_agruped

Index(['paginas_vistas', 'contenidos', 'visitas', 'pv_muro', 'contenidos_muro',
       'pv_premium', 'contenidos_premium', 'engagement', 'videos', 'rebotes',
       'tm_visita', 'paginas_vistas_amp', 'visitas_amp',
       'engagement_sin_rebote', 'tm_visita_sin_rebote', 'n_salta_metered',
       'n_comentarios_enviados'],
      dtype='object')

In [11]:
users['tipo_login'].value_counts()

suscriptor    744
anonimo       150
registrado     81
periodista     20
trial           5
Name: tipo_login, dtype: int64

In [12]:
users['genero'].value_counts()

m            378
masculino    176
f            134
femenino      61
u              9
Name: genero, dtype: int64

In [530]:
users.loc[users['genero'] == 'masculino', ['genero']] = 'm'

/Users/raulgomez/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [514]:
#users['genero'] = users['genero'].replace(['masculino'],'m').replace('femenino','f').fillna('u')
#users.loc[users['genero'] == 'masculino', 'genero'] = 'm'
#users.loc[users['genero'] == 'femenino', 'genero'] = 'f'
#users['genero'].fillna('u', inplace=True)
#users['genero'] = np.where(users['genero'] == 'masculino','m',users['genero'])
users.loc[users['genero'] == 'masculino', ['genero']] = 'm'
#users[users['genero'] == 'femenino' ].loc[:, ['genero']] = 'f'

/Users/raulgomez/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [498]:
users['genero']

0              m
1              m
2              m
3            NaN
4              m
         ...
995            u
996            m
997            m
998    masculino
999            f
Name: genero, Length: 975, dtype: object

In [3]:
from users import Users

In [4]:
users = Users(data_root='../data/')
users.set_data()

In [5]:
users.users

,usuario,cookie,id_gigya,cod_postal,edad,genero,tipo_login,tipo_navega,tipo_dispositivo,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion
0,78417469351791975736169845891825711610,75535567505083556960762774790239330639,006968865c844a2e9316d9c086970630,39310,33.0,m,anonimo,web,mobile,2,2,2,2,2,0,0,1.000000,0,2,NaN,2.0,2.0,NaN,NaN,0,0.0,2020-06-01
1,52425750985802126442668436210298346684,16451832170087691251533166194581228111,006968865c844a2e9316d9c086970630,39310,33.0,m,suscriptor,web,mobile,1,1,1,0,0,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2020-06-01
2,45307505850961913832102651929863475916,00428307531488269410201290079250673864,006968865c844a2e9316d9c086970630,39310,33.0,m,suscriptor,web,pc,28,12,3,8,8,0,0,9.333333,3,0,9.261111,0.0,0.0,0.107143,9.261111,0,0.0,2020-06-01
3,33997985857765348904611693873583459292,63017210247913765581302871108862417773,009875f699314f598cedd75d588bfbbe,39004,43.0,NaN,suscriptor,web,mobile,7,4,1,6,3,0,0,7.000000,0,0,5.216667,0.0,0.0,0.142857,5.216667,0,0.0,2020-06-01
4,81296065445598473884383853852904739808,36203010557659682852636129438578529630,00a488b7424641c683cd665375ba0838,39540,75.0,m,suscriptor,web,pc,69,29,1,21,12,2,2,69.000000,1,0,48.550000,0.0,0.0,0.014493,48.550000,0,0.0,2020-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,17820994817216648438804946554425008355,44495317034553139352426147463302322716,a0c2df0a9d8442abb1dd69bb41187dc9,39610,38.0,u,registrado,web,mobile,38,7,2,0,0,0,0,19.000000,0,1,53.841667,0.0,0.0,0.027027,107.683333,0,0.0,2020-06-01
996,11811022866339183337792737204324697793,37040961244367417731553356128723336342,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,m,suscriptor,web,mobile,13,1,6,0,0,0,0,2.166667,0,2,9.805556,0.0,0.0,0.363636,14.708333,0,0.0,2020-06-01
997,6239321634259109655492988748579986367,15515126231343402701698194286031773275,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,m,suscriptor,web,pc,3,1,1,0,0,0,0,3.000000,0,0,30.550000,0.0,0.0,0.333333,30.550000,0,0.0,2020-06-01
998,32702980139170587786917530168491791173,NaN,a13b758bd8e34e1d910ef3166fc0c849,28020,76.0,masculino,registrado,app,mobile,2,1,1,0,0,0,0,2.000000,0,0,0.600000,NaN,NaN,NaN,0.600000,0,NaN,2020-06-01
999,7196986871911805005198212641853412597,19100380572136867181619132953201971649,a17cf964c6a94ee8966e01cf79afb838,39011,35.0,f,suscriptor,web,mobile,3,2,2,0,0,0,0,1.500000,0,1,0.375000,0.0,0.0,0.500000,0.750000,0,0.0,2020-06-01

In [6]:
users.clean_data()

In [7]:
users.users

,id_gigya,cod_postal,edad,paginas_vistas,contenidos,visitas,pv_muro,contenidos_muro,pv_premium,contenidos_premium,engagement,videos,rebotes,tm_visita,paginas_vistas_amp,visitas_amp,engagement_sin_rebote,tm_visita_sin_rebote,n_salta_metered,n_comentarios_enviados,fecha_navegacion,anonimo,registrado,suscriptor,app,web,mobile,pc,f,m,u
0,006968865c844a2e9316d9c086970630,39310,33.0,2,2,2,2,2,0,0,1.000000,0,2,NaN,2.0,2.0,NaN,NaN,0,0.0,2020-06-01,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
1,006968865c844a2e9316d9c086970630,39310,33.0,1,1,1,0,0,0,0,1.000000,0,1,NaN,0.0,0.0,NaN,NaN,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,006968865c844a2e9316d9c086970630,39310,33.0,28,12,3,8,8,0,0,9.333333,3,0,9.261111,0.0,0.0,0.107143,9.261111,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,009875f699314f598cedd75d588bfbbe,39004,43.0,7,4,1,6,3,0,0,7.000000,0,0,5.216667,0.0,0.0,0.142857,5.216667,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,00a488b7424641c683cd665375ba0838,39540,75.0,69,29,1,21,12,2,2,69.000000,1,0,48.550000,0.0,0.0,0.014493,48.550000,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,a0c2df0a9d8442abb1dd69bb41187dc9,39610,38.0,38,7,2,0,0,0,0,19.000000,0,1,53.841667,0.0,0.0,0.027027,107.683333,0,0.0,2020-06-01,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
971,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,13,1,6,0,0,0,0,2.166667,0,2,9.805556,0.0,0.0,0.363636,14.708333,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
972,a0ec428cfe7d4c9cb6062e7a044d44cb,39002,30.0,3,1,1,0,0,0,0,3.000000,0,0,30.550000,0.0,0.0,0.333333,30.550000,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
973,a13b758bd8e34e1d910ef3166fc0c849,28020,76.0,2,1,1,0,0,0,0,2.000000,0,0,0.600000,NaN,NaN,NaN,0.600000,0,NaN,2020-06-01,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
974,a17cf964c6a94ee8966e01cf79afb838,39011,35.0,3,2,2,0,0,0,0,1.500000,0,1,0.375000,0.0,0.0,0.500000,0.750000,0,0.0,2020-06-01,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [11]:
users.users['edad'].isna().value_counts()

False    793
True     182
Name: edad, dtype: int64

In [12]:
users.users['id_gigya'].isna().value_counts()

False    975
Name: id_gigya, dtype: int64

In [13]:
users.users['cod_postal'].isna().value_counts()

False    833
True     142
Name: cod_postal, dtype: int64

In [22]:
users.users['engagement'].isna().value_counts()

False    975
Name: engagement, dtype: int64

In [24]:
users.users['rebotes'].isna().value_counts()

False    975
Name: rebotes, dtype: int64

In [ ]:
users.users['cod_postal'].isna().value_counts()

In [38]:
for c in users.users.columns:
    if (len(users.users[c].isna().value_counts()) > 1):
        print (c)
        print (users.users[c].isna().value_counts())

cod_postal
False    833
True     142
Name: cod_postal, dtype: int64
edad
False    793
True     182
Name: edad, dtype: int64
tm_visita
False    796
True     179
Name: tm_visita, dtype: int64
paginas_vistas_amp
False    712
True     263
Name: paginas_vistas_amp, dtype: int64
visitas_amp
False    712
True     263
Name: visitas_amp, dtype: int64
engagement_sin_rebote
False    544
True     431
Name: engagement_sin_rebote, dtype: int64
tm_visita_sin_rebote
False    774
True     201
Name: tm_visita_sin_rebote, dtype: int64
n_comentarios_enviados
False    712
True     263
Name: n_comentarios_enviados, dtype: int64